# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser>=3.0,<4.0
  # Set default python version to 3.10 - repo2docker sets it to 3.7 instead by default,
  # which can limit us to older package versions
  - python=3.10
  # Everyone wants to use nbgitpuller for everything, so let's do that
  - nbgitpuller=1.1.*
  # Add other packages here
  - numpy=1.22.4
  - xarray=2022.3.0
  - scipy=1.8.1
  - matplotlib=3.5.2
  - zarr=2.11.3
  - intake=0.6.5
  - xrft
  - xhistogram
  - intake
  - intake-xarray
  - numpy_groupies
  - cmocean
  - gcm_filters
  - aiohttp
  - requests
  - s3fs
  - cryptography=38.0.2
